# Importing Library

In [12]:
import pandas as pd

# Importing Data

In [26]:
df1=pd.read_excel(r"C:\Users\iamri\Downloads\Customer Call List.xlsx")
df1

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes,False
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,NaN,True
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No,True
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,True
6,1007,Jeff,Winger,NaN,1209 South Street,No,No,False
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No,False
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN,False
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,True
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No,True
11,1012,Harry,...Potter,7066950392,2394 Hogwarts Avenue,Y,NaN,True
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,False
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No,False
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No,False
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No,False
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN,True
18,1019,Creed,Braton,N/a,N/a,N/a,Yes,True
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True
20,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True

# Droping Duplicate and Not useful Columns

In [27]:
df1.drop(columns='Not_Useful_Column',inplace=True)
df1= df1.drop_duplicates()
df1

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,NaN
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes
6,1007,Jeff,Winger,NaN,1209 South Street,No,No
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No
11,1012,Harry,...Potter,7066950392,2394 Hogwarts Avenue,Y,NaN
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN
18,1019,Creed,Braton,N/a,N/a,N/a,Yes
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N

# Using Strip Function

In [28]:
#df1['Last_Name']=df1['Last_Name'].str.lstrip('...')
#df1['Last_Name']=df1['Last_Name'].str.lstrip('/')
#df1['Last_Name']=df1['Last_Name'].str.rstrip('_')
df1['Last_Name']=df1['Last_Name'].str.strip('_./')
df1

C:\Users\iamri\AppData\Local\Temp\ipykernel_22404\2980873993.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['Last_Name']=df1['Last_Name'].str.strip('_./')

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes
2,1003,Walter,White,7066950392,298 Drugs Driveway,N,NaN
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes
6,1007,Jeff,Winger,NaN,1209 South Street,No,No
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No
11,1012,Harry,Potter,7066950392,2394 Hogwarts Avenue,Y,NaN
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No
14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,No
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN
18,1019,Creed,Braton,N/a,N/a,N/a,Yes
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N

# Removing Unwanted from Phone number

In [29]:
df1['Phone_Number']=df1['Phone_Number'].str.replace('[^a-zA-Z0-9]','')
df1

C:\Users\iamri\AppData\Local\Temp\ipykernel_22404\1487677198.py:1: FutureWarning: The default value of regex will change from True to False in a future version.
  df1['Phone_Number']=df1['Phone_Number'].str.replace('[^a-zA-Z0-9]','')
C:\Users\iamri\AppData\Local\Temp\ipykernel_22404\1487677198.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['Phone_Number']=df1['Phone_Number'].str.replace('[^a-zA-Z0-9]','')

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact
0,1001,Frodo,Baggins,1235455421,"123 Shire Lane, Shire",Yes,No
1,1002,Abed,Nadir,1236439775,93 West Main Street,No,Yes
2,1003,Walter,White,NaN,298 Drugs Driveway,N,NaN
3,1004,Dwight,Schrute,1235432345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y
4,1005,Jon,Snow,8766783469,123 Dragons Road,Y,No
5,1006,Ron,Swanson,3047622467,768 City Parkway,Yes,Yes
6,1007,Jeff,Winger,NaN,1209 South Street,No,No
7,1008,Sherlock,Holmes,8766783469,98 Clue Drive,N,No
8,1009,Gandalf,NaN,Na,123 Middle Earth,Yes,NaN
9,1010,Peter,Parker,1235455421,"25th Main Street, New York",Yes,No
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No
11,1012,Harry,Potter,NaN,2394 Hogwarts Avenue,Y,NaN
12,1013,Don,Draper,1235432345,2039 Main Street,Yes,N
13,1014,Leslie,Knope,8766783469,343 City Parkway,Yes,No
14,1015,Toby,Flenderson,3047622467,214 HR Avenue,N,No
15,1016,Ron,Weasley,1235455421,2395 Hogwarts Avenue,No,N
16,1017,Michael,Scott,1236439775,"121 Paper Avenue, Pennsylvania",Yes,No
17,1018,Clark,Kent,NaN,3498 Super Lane,Y,NaN
18,1019,Creed,Braton,Na,N/a,N/a,Yes
19,1020,Anakin,Skywalker,8766783469,"910 Tatooine Road, Tatooine",Yes,N

# Converting Phone Number to string

In [30]:
df1['Phone_Number']=df1['Phone_Number'].apply(lambda x: str(x))

C:\Users\iamri\AppData\Local\Temp\ipykernel_22404\726935487.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['Phone_Number']=df1['Phone_Number'].apply(lambda x: str(x))

# Formating The Phone Number

In [31]:
df1['Phone_Number']=df1['Phone_Number'].apply(lambda x: x[0:3] + '-' + x[3:6] + '-' + x[6:10])

C:\Users\iamri\AppData\Local\Temp\ipykernel_22404\1629731870.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['Phone_Number']=df1['Phone_Number'].apply(lambda x: x[0:3] + '-' + x[3:6] + '-' + x[6:10])

In [32]:
df1['Phone_Number']=df1['Phone_Number'].str.replace('--','')
df1

C:\Users\iamri\AppData\Local\Temp\ipykernel_22404\3823796708.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['Phone_Number']=df1['Phone_Number'].str.replace('--','')

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No
1,1002,Abed,Nadir,123-643-9775,93 West Main Street,No,Yes
2,1003,Walter,White,nan,298 Drugs Driveway,N,NaN
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y
4,1005,Jon,Snow,876-678-3469,123 Dragons Road,Y,No
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes
6,1007,Jeff,Winger,nan,1209 South Street,No,No
7,1008,Sherlock,Holmes,876-678-3469,98 Clue Drive,N,No
8,1009,Gandalf,NaN,Na,123 Middle Earth,Yes,NaN
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No
10,1011,Samwise,Gamgee,nan,"612 Shire Lane, Shire",Yes,No
11,1012,Harry,Potter,nan,2394 Hogwarts Avenue,Y,NaN
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N
13,1014,Leslie,Knope,876-678-3469,343 City Parkway,Yes,No
14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,No
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N
16,1017,Michael,Scott,123-643-9775,"121 Paper Avenue, Pennsylvania",Yes,No
17,1018,Clark,Kent,nan,3498 Super Lane,Y,NaN
18,1019,Creed,Braton,Na,N/a,N/a,Yes
19,1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Yes,N

# Formating House Column

In [33]:
df1[['House_No.','House_Address']]=df1['Address'].str.split(' ',1,expand=True)
df1

C:\Users\iamri\AppData\Local\Temp\ipykernel_22404\185718921.py:1: FutureWarning: In a future version of pandas all arguments of StringMethods.split except for the argument 'pat' will be keyword-only.
  df1[['House_No.','House_Address']]=df1['Address'].str.split(' ',1,expand=True)
C:\Users\iamri\AppData\Local\Temp\ipykernel_22404\185718921.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1[['House_No.','House_Address']]=df1['Address'].str.split(' ',1,expand=True)
C:\Users\iamri\AppData\Local\Temp\ipykernel_22404\185718921.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1[['House_No.','House_Address']]=df1['Address'].str.split(' ',1,expand=True)

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,House_No.,House_Address
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,123,"Shire Lane, Shire"
1,1002,Abed,Nadir,123-643-9775,93 West Main Street,No,Yes,93,West Main Street
2,1003,Walter,White,nan,298 Drugs Driveway,N,NaN,298,Drugs Driveway
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,980,"Paper Avenue, Pennsylvania, 18503"
4,1005,Jon,Snow,876-678-3469,123 Dragons Road,Y,No,123,Dragons Road
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,768,City Parkway
6,1007,Jeff,Winger,nan,1209 South Street,No,No,1209,South Street
7,1008,Sherlock,Holmes,876-678-3469,98 Clue Drive,N,No,98,Clue Drive
8,1009,Gandalf,NaN,Na,123 Middle Earth,Yes,NaN,123,Middle Earth
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,25th,"Main Street, New York"
10,1011,Samwise,Gamgee,nan,"612 Shire Lane, Shire",Yes,No,612,"Shire Lane, Shire"
11,1012,Harry,Potter,nan,2394 Hogwarts Avenue,Y,NaN,2394,Hogwarts Avenue
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,2039,Main Street
13,1014,Leslie,Knope,876-678-3469,343 City Parkway,Yes,No,343,City Parkway
14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,No,214,HR Avenue
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,2395,Hogwarts Avenue
16,1017,Michael,Scott,123-643-9775,"121 Paper Avenue, Pennsylvania",Yes,No,121,"Paper Avenue, Pennsylvania"
17,1018,Clark,Kent,nan,3498 Super Lane,Y,NaN,3498,Super Lane
18,1019,Creed,Braton,Na,N/a,N/a,Yes,N/a,None
19,1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Yes,N,910,"Tatooine Road, Tatooine"

In [34]:
df1[["Street_Name","City","Postal_Code"]]=df1["House_Address"].str.split(',',2,expand=True)
df1

C:\Users\iamri\AppData\Local\Temp\ipykernel_22404\3528032082.py:1: FutureWarning: In a future version of pandas all arguments of StringMethods.split except for the argument 'pat' will be keyword-only.
  df1[["Street_Name","City","Postal_Code"]]=df1["House_Address"].str.split(',',2,expand=True)
C:\Users\iamri\AppData\Local\Temp\ipykernel_22404\3528032082.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1[["Street_Name","City","Postal_Code"]]=df1["House_Address"].str.split(',',2,expand=True)
C:\Users\iamri\AppData\Local\Temp\ipykernel_22404\3528032082.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1[["Street_Name","City","Postal_Code"]]=df1["House_Address"].str.split(',',2,expand=True)
C:\Users\iamri\AppData\Local\Temp\ipykernel_22404\3528032082.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1[["Street_Name","City","Postal_Code"]]=df1["House_Address"].str.split(',',2,expand=True)

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,House_No.,House_Address,Street_Name,City,Postal_Code
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,123,"Shire Lane, Shire",Shire Lane,Shire,None
1,1002,Abed,Nadir,123-643-9775,93 West Main Street,No,Yes,93,West Main Street,West Main Street,None,None
2,1003,Walter,White,nan,298 Drugs Driveway,N,NaN,298,Drugs Driveway,Drugs Driveway,None,None
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,980,"Paper Avenue, Pennsylvania, 18503",Paper Avenue,Pennsylvania,18503
4,1005,Jon,Snow,876-678-3469,123 Dragons Road,Y,No,123,Dragons Road,Dragons Road,None,None
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,768,City Parkway,City Parkway,None,None
6,1007,Jeff,Winger,nan,1209 South Street,No,No,1209,South Street,South Street,None,None
7,1008,Sherlock,Holmes,876-678-3469,98 Clue Drive,N,No,98,Clue Drive,Clue Drive,None,None
8,1009,Gandalf,NaN,Na,123 Middle Earth,Yes,NaN,123,Middle Earth,Middle Earth,None,None
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,25th,"Main Street, New York",Main Street,New York,None
10,1011,Samwise,Gamgee,nan,"612 Shire Lane, Shire",Yes,No,612,"Shire Lane, Shire",Shire Lane,Shire,None
11,1012,Harry,Potter,nan,2394 Hogwarts Avenue,Y,NaN,2394,Hogwarts Avenue,Hogwarts Avenue,None,None
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,2039,Main Street,Main Street,None,None
13,1014,Leslie,Knope,876-678-3469,343 City Parkway,Yes,No,343,City Parkway,City Parkway,None,None
14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,No,214,HR Avenue,HR Avenue,None,None
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,2395,Hogwarts Avenue,Hogwarts Avenue,None,None
16,1017,Michael,Scott,123-643-9775,"121 Paper Avenue, Pennsylvania",Yes,No,121,"Paper Avenue, Pennsylvania",Paper Avenue,Pennsylvania,None
17,1018,Clark,Kent,nan,3498 Super Lane,Y,NaN,3498,Super Lane,Super Lane,None,None
18,1019,Creed,Braton,Na,N/a,N/a,Yes,N/a,None,None,None,None
19,1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Yes,N,910,"Tatooine Road, Tatooine",Tatooine Road,Tatooine,None

In [35]:
df1 = df1.drop(columns=["Address","House_Address"])
df1

,CustomerID,First_Name,Last_Name,Phone_Number,Paying Customer,Do_Not_Contact,House_No.,Street_Name,City,Postal_Code
0,1001,Frodo,Baggins,123-545-5421,Yes,No,123,Shire Lane,Shire,None
1,1002,Abed,Nadir,123-643-9775,No,Yes,93,West Main Street,None,None
2,1003,Walter,White,nan,N,NaN,298,Drugs Driveway,None,None
3,1004,Dwight,Schrute,123-543-2345,Yes,Y,980,Paper Avenue,Pennsylvania,18503
4,1005,Jon,Snow,876-678-3469,Y,No,123,Dragons Road,None,None
5,1006,Ron,Swanson,304-762-2467,Yes,Yes,768,City Parkway,None,None
6,1007,Jeff,Winger,nan,No,No,1209,South Street,None,None
7,1008,Sherlock,Holmes,876-678-3469,N,No,98,Clue Drive,None,None
8,1009,Gandalf,NaN,Na,Yes,NaN,123,Middle Earth,None,None
9,1010,Peter,Parker,123-545-5421,Yes,No,25th,Main Street,New York,None
10,1011,Samwise,Gamgee,nan,Yes,No,612,Shire Lane,Shire,None
11,1012,Harry,Potter,nan,Y,NaN,2394,Hogwarts Avenue,None,None
12,1013,Don,Draper,123-543-2345,Yes,N,2039,Main Street,None,None
13,1014,Leslie,Knope,876-678-3469,Yes,No,343,City Parkway,None,None
14,1015,Toby,Flenderson,304-762-2467,N,No,214,HR Avenue,None,None
15,1016,Ron,Weasley,123-545-5421,No,N,2395,Hogwarts Avenue,None,None
16,1017,Michael,Scott,123-643-9775,Yes,No,121,Paper Avenue,Pennsylvania,None
17,1018,Clark,Kent,nan,Y,NaN,3498,Super Lane,None,None
18,1019,Creed,Braton,Na,N/a,Yes,N/a,None,None,None
19,1020,Anakin,Skywalker,876-678-3469,Yes,N,910,Tatooine Road,Tatooine,None

# Removing nan and Na From Phone Number and Last Name

In [41]:
df1['Phone_Number']=df1['Phone_Number'].str.replace('nan','')
df1['Phone_Number']=df1['Phone_Number'].str.replace('Na','')
df1['Last_Name']= df1['Last_Name'].apply(lambda x : str(x))
df1['Last_Name']= df1['Last_Name'].str.replace("NaN","")
df1['Last_Name']= df1['Last_Name'].str.replace("nan","")
df1

,CustomerID,First_Name,Last_Name,Phone_Number,Paying Customer,Do_Not_Contact,House_No.,Street_Name,City,Postal_Code
0,1001,Frodo,Baggins,123-545-5421,Yes,No,123,Shire Lane,Shire,None
1,1002,Abed,Nadir,123-643-9775,No,Yes,93,West Main Street,None,None
2,1003,Walter,White,,N,NaN,298,Drugs Driveway,None,None
3,1004,Dwight,Schrute,123-543-2345,Yes,Y,980,Paper Avenue,Pennsylvania,18503
4,1005,Jon,Snow,876-678-3469,Y,No,123,Dragons Road,None,None
5,1006,Ron,Swanson,304-762-2467,Yes,Yes,768,City Parkway,None,None
6,1007,Jeff,Winger,,No,No,1209,South Street,None,None
7,1008,Sherlock,Holmes,876-678-3469,N,No,98,Clue Drive,None,None
8,1009,Gandalf,,,Yes,NaN,123,Middle Earth,None,None
9,1010,Peter,Parker,123-545-5421,Yes,No,25th,Main Street,New York,None
10,1011,Samwise,Gamgee,,Yes,No,612,Shire Lane,Shire,None
11,1012,Harry,Potter,,Y,NaN,2394,Hogwarts Avenue,None,None
12,1013,Don,Draper,123-543-2345,Yes,N,2039,Main Street,None,None
13,1014,Leslie,Knope,876-678-3469,Yes,No,343,City Parkway,None,None
14,1015,Toby,Flenderson,304-762-2467,N,No,214,HR Avenue,None,None
15,1016,Ron,Weasley,123-545-5421,No,N,2395,Hogwarts Avenue,None,None
16,1017,Michael,Scott,123-643-9775,Yes,No,121,Paper Avenue,Pennsylvania,None
17,1018,Clark,Kent,,Y,NaN,3498,Super Lane,None,None
18,1019,Creed,Braton,,N/a,Yes,N/a,None,None,None
19,1020,Anakin,Skywalker,876-678-3469,Yes,N,910,Tatooine Road,Tatooine,None

# Adding First and Last name

In [ ]:
df1["First_Name"]=df1["First_Name"]+' '+df1["Last_Name"]
df1

In [43]:
df1=df1.drop(columns='Last_Name')
df1

,CustomerID,First_Name,Phone_Number,Paying Customer,Do_Not_Contact,House_No.,Street_Name,City,Postal_Code
0,1001,Frodo Baggins,123-545-5421,Yes,No,123,Shire Lane,Shire,None
1,1002,Abed Nadir,123-643-9775,No,Yes,93,West Main Street,None,None
2,1003,Walter White,,N,NaN,298,Drugs Driveway,None,None
3,1004,Dwight Schrute,123-543-2345,Yes,Y,980,Paper Avenue,Pennsylvania,18503
4,1005,Jon Snow,876-678-3469,Y,No,123,Dragons Road,None,None
5,1006,Ron Swanson,304-762-2467,Yes,Yes,768,City Parkway,None,None
6,1007,Jeff Winger,,No,No,1209,South Street,None,None
7,1008,Sherlock Holmes,876-678-3469,N,No,98,Clue Drive,None,None
8,1009,Gandalf,,Yes,NaN,123,Middle Earth,None,None
9,1010,Peter Parker,123-545-5421,Yes,No,25th,Main Street,New York,None
10,1011,Samwise Gamgee,,Yes,No,612,Shire Lane,Shire,None
11,1012,Harry Potter,,Y,NaN,2394,Hogwarts Avenue,None,None
12,1013,Don Draper,123-543-2345,Yes,N,2039,Main Street,None,None
13,1014,Leslie Knope,876-678-3469,Yes,No,343,City Parkway,None,None
14,1015,Toby Flenderson,304-762-2467,N,No,214,HR Avenue,None,None
15,1016,Ron Weasley,123-545-5421,No,N,2395,Hogwarts Avenue,None,None
16,1017,Michael Scott,123-643-9775,Yes,No,121,Paper Avenue,Pennsylvania,None
17,1018,Clark Kent,,Y,NaN,3498,Super Lane,None,None
18,1019,Creed Braton,,N/a,Yes,N/a,None,None,None
19,1020,Anakin Skywalker,876-678-3469,Yes,N,910,Tatooine Road,Tatooine,None

In [17]:
#df1["Postal_Code"]=df1["Postal_Code"].str.replace('None',' ')
#df1

,CustomerID,First_Name,Phone_Number,Paying Customer,Do_Not_Contact,House_No.,Street_Name,City,Postal_Code
0,1001,Frodo Baggins,123-545-5421,Yes,No,123,Shire Lane,Shire,None
1,1002,Abed Nadir,123-643-9775,No,Yes,93,West Main Street,None,None
2,1003,Walter White,--,N,NaN,298,Drugs Driveway,None,None
3,1004,Dwight Schrute,123-543-2345,Yes,Y,980,Paper Avenue,Pennsylvania,18503
4,1005,Jon Snow,876-678-3469,Y,No,123,Dragons Road,None,None
5,1006,Ron Swanson,304-762-2467,Yes,Yes,768,City Parkway,None,None
6,1007,Jeff Winger,--,No,No,1209,South Street,None,None
7,1008,Sherlock Holmes,876-678-3469,N,No,98,Clue Drive,None,None
8,1009,NaN,--,Yes,NaN,123,Middle Earth,None,None
9,1010,Peter Parker,123-545-5421,Yes,No,25th,Main Street,New York,None
10,1011,Samwise Gamgee,--,Yes,No,612,Shire Lane,Shire,None
11,1012,Harry Potter,--,Y,NaN,2394,Hogwarts Avenue,None,None
12,1013,Don Draper,123-543-2345,Yes,N,2039,Main Street,None,None
13,1014,Leslie Knope,876-678-3469,Yes,No,343,City Parkway,None,None
14,1015,Toby Flenderson,304-762-2467,N,No,214,HR Avenue,None,None
15,1016,Ron Weasley,123-545-5421,No,N,2395,Hogwarts Avenue,None,None
16,1017,Michael Scott,123-643-9775,Yes,No,121,Paper Avenue,Pennsylvania,None
17,1018,Clark Kent,--,Y,NaN,3498,Super Lane,None,None
18,1019,Creed Braton,--,N/a,Yes,N/a,None,None,None
19,1020,Anakin Skywalker,876-678-3469,Yes,N,910,Tatooine Road,Tatooine,None
20,1020,Anakin Skywalker,876-678-3469,Yes,N,910,Tatooine Road,Tatooine,None

# Formating City

In [44]:
df1["Postal_Code"]=df1["Postal_Code"].apply(lambda x : str(x))
df1["City"]=df1["City"].apply(lambda x : str(x))

In [45]:
df1['City']=df1['City'].str.replace('None',' ')
df1

,CustomerID,First_Name,Phone_Number,Paying Customer,Do_Not_Contact,House_No.,Street_Name,City,Postal_Code
0,1001,Frodo Baggins,123-545-5421,Yes,No,123,Shire Lane,Shire,None
1,1002,Abed Nadir,123-643-9775,No,Yes,93,West Main Street,,None
2,1003,Walter White,,N,NaN,298,Drugs Driveway,,None
3,1004,Dwight Schrute,123-543-2345,Yes,Y,980,Paper Avenue,Pennsylvania,18503
4,1005,Jon Snow,876-678-3469,Y,No,123,Dragons Road,,None
5,1006,Ron Swanson,304-762-2467,Yes,Yes,768,City Parkway,,None
6,1007,Jeff Winger,,No,No,1209,South Street,,None
7,1008,Sherlock Holmes,876-678-3469,N,No,98,Clue Drive,,None
8,1009,Gandalf,,Yes,NaN,123,Middle Earth,,None
9,1010,Peter Parker,123-545-5421,Yes,No,25th,Main Street,New York,None
10,1011,Samwise Gamgee,,Yes,No,612,Shire Lane,Shire,None
11,1012,Harry Potter,,Y,NaN,2394,Hogwarts Avenue,,None
12,1013,Don Draper,123-543-2345,Yes,N,2039,Main Street,,None
13,1014,Leslie Knope,876-678-3469,Yes,No,343,City Parkway,,None
14,1015,Toby Flenderson,304-762-2467,N,No,214,HR Avenue,,None
15,1016,Ron Weasley,123-545-5421,No,N,2395,Hogwarts Avenue,,None
16,1017,Michael Scott,123-643-9775,Yes,No,121,Paper Avenue,Pennsylvania,None
17,1018,Clark Kent,,Y,NaN,3498,Super Lane,,None
18,1019,Creed Braton,,N/a,Yes,N/a,None,,None
19,1020,Anakin Skywalker,876-678-3469,Yes,N,910,Tatooine Road,Tatooine,None

# Formating Paying Customer and Do not Contact

In [46]:
df1['Paying Customer'] = df1['Paying Customer'].str.replace("Yes","Y")
df1['Paying Customer'] = df1['Paying Customer'].str.replace("No","N")
df1

,CustomerID,First_Name,Phone_Number,Paying Customer,Do_Not_Contact,House_No.,Street_Name,City,Postal_Code
0,1001,Frodo Baggins,123-545-5421,Y,No,123,Shire Lane,Shire,None
1,1002,Abed Nadir,123-643-9775,N,Yes,93,West Main Street,,None
2,1003,Walter White,,N,NaN,298,Drugs Driveway,,None
3,1004,Dwight Schrute,123-543-2345,Y,Y,980,Paper Avenue,Pennsylvania,18503
4,1005,Jon Snow,876-678-3469,Y,No,123,Dragons Road,,None
5,1006,Ron Swanson,304-762-2467,Y,Yes,768,City Parkway,,None
6,1007,Jeff Winger,,N,No,1209,South Street,,None
7,1008,Sherlock Holmes,876-678-3469,N,No,98,Clue Drive,,None
8,1009,Gandalf,,Y,NaN,123,Middle Earth,,None
9,1010,Peter Parker,123-545-5421,Y,No,25th,Main Street,New York,None
10,1011,Samwise Gamgee,,Y,No,612,Shire Lane,Shire,None
11,1012,Harry Potter,,Y,NaN,2394,Hogwarts Avenue,,None
12,1013,Don Draper,123-543-2345,Y,N,2039,Main Street,,None
13,1014,Leslie Knope,876-678-3469,Y,No,343,City Parkway,,None
14,1015,Toby Flenderson,304-762-2467,N,No,214,HR Avenue,,None
15,1016,Ron Weasley,123-545-5421,N,N,2395,Hogwarts Avenue,,None
16,1017,Michael Scott,123-643-9775,Y,No,121,Paper Avenue,Pennsylvania,None
17,1018,Clark Kent,,Y,NaN,3498,Super Lane,,None
18,1019,Creed Braton,,N/a,Yes,N/a,None,,None
19,1020,Anakin Skywalker,876-678-3469,Y,N,910,Tatooine Road,Tatooine,None

In [47]:
df1['Do_Not_Contact'] = df1['Do_Not_Contact'].str.replace("Yes","Y")
df1['Do_Not_Contact'] = df1['Do_Not_Contact'].str.replace("No","N")
df1

,CustomerID,First_Name,Phone_Number,Paying Customer,Do_Not_Contact,House_No.,Street_Name,City,Postal_Code
0,1001,Frodo Baggins,123-545-5421,Y,N,123,Shire Lane,Shire,None
1,1002,Abed Nadir,123-643-9775,N,Y,93,West Main Street,,None
2,1003,Walter White,,N,NaN,298,Drugs Driveway,,None
3,1004,Dwight Schrute,123-543-2345,Y,Y,980,Paper Avenue,Pennsylvania,18503
4,1005,Jon Snow,876-678-3469,Y,N,123,Dragons Road,,None
5,1006,Ron Swanson,304-762-2467,Y,Y,768,City Parkway,,None
6,1007,Jeff Winger,,N,N,1209,South Street,,None
7,1008,Sherlock Holmes,876-678-3469,N,N,98,Clue Drive,,None
8,1009,Gandalf,,Y,NaN,123,Middle Earth,,None
9,1010,Peter Parker,123-545-5421,Y,N,25th,Main Street,New York,None
10,1011,Samwise Gamgee,,Y,N,612,Shire Lane,Shire,None
11,1012,Harry Potter,,Y,NaN,2394,Hogwarts Avenue,,None
12,1013,Don Draper,123-543-2345,Y,N,2039,Main Street,,None
13,1014,Leslie Knope,876-678-3469,Y,N,343,City Parkway,,None
14,1015,Toby Flenderson,304-762-2467,N,N,214,HR Avenue,,None
15,1016,Ron Weasley,123-545-5421,N,N,2395,Hogwarts Avenue,,None
16,1017,Michael Scott,123-643-9775,Y,N,121,Paper Avenue,Pennsylvania,None
17,1018,Clark Kent,,Y,NaN,3498,Super Lane,,None
18,1019,Creed Braton,,N/a,Y,N/a,None,,None
19,1020,Anakin Skywalker,876-678-3469,Y,N,910,Tatooine Road,Tatooine,None

In [49]:
df1['Paying Customer']=df1['Paying Customer'].str.replace("N/a",'')
df1

,CustomerID,First_Name,Phone_Number,Paying Customer,Do_Not_Contact,House_No.,Street_Name,City,Postal_Code
0,1001,Frodo Baggins,123-545-5421,Y,N,123,Shire Lane,Shire,None
1,1002,Abed Nadir,123-643-9775,N,Y,93,West Main Street,,None
2,1003,Walter White,,N,NaN,298,Drugs Driveway,,None
3,1004,Dwight Schrute,123-543-2345,Y,Y,980,Paper Avenue,Pennsylvania,18503
4,1005,Jon Snow,876-678-3469,Y,N,123,Dragons Road,,None
5,1006,Ron Swanson,304-762-2467,Y,Y,768,City Parkway,,None
6,1007,Jeff Winger,,N,N,1209,South Street,,None
7,1008,Sherlock Holmes,876-678-3469,N,N,98,Clue Drive,,None
8,1009,Gandalf,,Y,NaN,123,Middle Earth,,None
9,1010,Peter Parker,123-545-5421,Y,N,25th,Main Street,New York,None
10,1011,Samwise Gamgee,,Y,N,612,Shire Lane,Shire,None
11,1012,Harry Potter,,Y,NaN,2394,Hogwarts Avenue,,None
12,1013,Don Draper,123-543-2345,Y,N,2039,Main Street,,None
13,1014,Leslie Knope,876-678-3469,Y,N,343,City Parkway,,None
14,1015,Toby Flenderson,304-762-2467,N,N,214,HR Avenue,,None
15,1016,Ron Weasley,123-545-5421,N,N,2395,Hogwarts Avenue,,None
16,1017,Michael Scott,123-643-9775,Y,N,121,Paper Avenue,Pennsylvania,None
17,1018,Clark Kent,,Y,NaN,3498,Super Lane,,None
18,1019,Creed Braton,,,Y,N/a,None,,None
19,1020,Anakin Skywalker,876-678-3469,Y,N,910,Tatooine Road,Tatooine,None

# Droping Empty Phone Number Columns

In [51]:
for x in df1.index :
    if df1.loc[x,"Phone_Number"] == "":
        df1.drop(x,inplace=True)

df1

,CustomerID,First_Name,Phone_Number,Paying Customer,Do_Not_Contact,House_No.,Street_Name,City,Postal_Code
0,1001,Frodo Baggins,123-545-5421,Y,N,123,Shire Lane,Shire,None
1,1002,Abed Nadir,123-643-9775,N,Y,93,West Main Street,,None
3,1004,Dwight Schrute,123-543-2345,Y,Y,980,Paper Avenue,Pennsylvania,18503
4,1005,Jon Snow,876-678-3469,Y,N,123,Dragons Road,,None
5,1006,Ron Swanson,304-762-2467,Y,Y,768,City Parkway,,None
7,1008,Sherlock Holmes,876-678-3469,N,N,98,Clue Drive,,None
9,1010,Peter Parker,123-545-5421,Y,N,25th,Main Street,New York,None
12,1013,Don Draper,123-543-2345,Y,N,2039,Main Street,,None
13,1014,Leslie Knope,876-678-3469,Y,N,343,City Parkway,,None
14,1015,Toby Flenderson,304-762-2467,N,N,214,HR Avenue,,None
15,1016,Ron Weasley,123-545-5421,N,N,2395,Hogwarts Avenue,,None
16,1017,Michael Scott,123-643-9775,Y,N,121,Paper Avenue,Pennsylvania,None
19,1020,Anakin Skywalker,876-678-3469,Y,N,910,Tatooine Road,Tatooine,None

# Droping Y in Do not Contact

In [55]:
for x in df1.index :
    if df1.loc[x,"Do_Not_Contact"] == 'Y':
        df1.drop(x, inplace=True)

In [79]:
df1

,CustomerID,First_Name,Phone_Number,Paying Customer,Do_Not_Contact,House_No.,Street_Name,City,Postal_Code
0,1001,Frodo Baggins,123-545-5421,Y,N,123,Shire Lane,Shire,
4,1005,Jon Snow,876-678-3469,Y,N,123,Dragons Road,,
7,1008,Sherlock Holmes,876-678-3469,N,N,98,Clue Drive,,
9,1010,Peter Parker,123-545-5421,Y,N,25th,Main Street,New York,
12,1013,Don Draper,123-543-2345,Y,N,2039,Main Street,,
13,1014,Leslie Knope,876-678-3469,Y,N,343,City Parkway,,
14,1015,Toby Flenderson,304-762-2467,N,N,214,HR Avenue,,
15,1016,Ron Weasley,123-545-5421,N,N,2395,Hogwarts Avenue,,
16,1017,Michael Scott,123-643-9775,Y,N,121,Paper Avenue,Pennsylvania,
19,1020,Anakin Skywalker,876-678-3469,Y,N,910,Tatooine Road,Tatooine,
20,1020,Anakin Skywalker,876-678-3469,Y,N,910,Tatooine Road,Tatooine,

In [56]:
df1.reset_index(inplace=True,drop=True)
df1

,CustomerID,First_Name,Phone_Number,House_No.,Street_Name,City,Paying Customer,Do_Not_Contact
0,1001,Frodo Baggins,123-545-5421,123,Shire Lane,Shire,Y,N
1,1005,Jon Snow,876-678-3469,123,Dragons Road,,Y,N
2,1008,Sherlock Holmes,876-678-3469,98,Clue Drive,,N,N
3,1010,Peter Parker,123-545-5421,25th,Main Street,New York,Y,N
4,1013,Don Draper,123-543-2345,2039,Main Street,,Y,N
5,1014,Leslie Knope,876-678-3469,343,City Parkway,,Y,N
6,1015,Toby Flenderson,304-762-2467,214,HR Avenue,,N,N
7,1016,Ron Weasley,123-545-5421,2395,Hogwarts Avenue,,N,N
8,1017,Michael Scott,123-643-9775,121,Paper Avenue,Pennsylvania,Y,N
9,1020,Anakin Skywalker,876-678-3469,910,Tatooine Road,Tatooine,Y,N

# Reindexing colunmns

In [57]:
df1=df1.reindex(columns=['CustomerID','First_Name','Phone_Number','House_No.','Street_Name','City','Paying Customer','Do_Not_Contact'])
df1

,CustomerID,First_Name,Phone_Number,House_No.,Street_Name,City,Paying Customer,Do_Not_Contact
0,1001,Frodo Baggins,123-545-5421,123,Shire Lane,Shire,Y,N
1,1005,Jon Snow,876-678-3469,123,Dragons Road,,Y,N
2,1008,Sherlock Holmes,876-678-3469,98,Clue Drive,,N,N
3,1010,Peter Parker,123-545-5421,25th,Main Street,New York,Y,N
4,1013,Don Draper,123-543-2345,2039,Main Street,,Y,N
5,1014,Leslie Knope,876-678-3469,343,City Parkway,,Y,N
6,1015,Toby Flenderson,304-762-2467,214,HR Avenue,,N,N
7,1016,Ron Weasley,123-545-5421,2395,Hogwarts Avenue,,N,N
8,1017,Michael Scott,123-643-9775,121,Paper Avenue,Pennsylvania,Y,N
9,1020,Anakin Skywalker,876-678-3469,910,Tatooine Road,Tatooine,Y,N

# Renaming Name Column

In [58]:
df1.rename(columns={'First_Name':'Full_Name'},inplace=True)
df1

,CustomerID,Full_Name,Phone_Number,House_No.,Street_Name,City,Paying Customer,Do_Not_Contact
0,1001,Frodo Baggins,123-545-5421,123,Shire Lane,Shire,Y,N
1,1005,Jon Snow,876-678-3469,123,Dragons Road,,Y,N
2,1008,Sherlock Holmes,876-678-3469,98,Clue Drive,,N,N
3,1010,Peter Parker,123-545-5421,25th,Main Street,New York,Y,N
4,1013,Don Draper,123-543-2345,2039,Main Street,,Y,N
5,1014,Leslie Knope,876-678-3469,343,City Parkway,,Y,N
6,1015,Toby Flenderson,304-762-2467,214,HR Avenue,,N,N
7,1016,Ron Weasley,123-545-5421,2395,Hogwarts Avenue,,N,N
8,1017,Michael Scott,123-643-9775,121,Paper Avenue,Pennsylvania,Y,N
9,1020,Anakin Skywalker,876-678-3469,910,Tatooine Road,Tatooine,Y,N

#  Final output

In [60]:
df1

,CustomerID,Full_Name,Phone_Number,House_No.,Street_Name,City,Paying Customer,Do_Not_Contact
0,1001,Frodo Baggins,123-545-5421,123,Shire Lane,Shire,Y,N
1,1005,Jon Snow,876-678-3469,123,Dragons Road,,Y,N
2,1008,Sherlock Holmes,876-678-3469,98,Clue Drive,,N,N
3,1010,Peter Parker,123-545-5421,25th,Main Street,New York,Y,N
4,1013,Don Draper,123-543-2345,2039,Main Street,,Y,N
5,1014,Leslie Knope,876-678-3469,343,City Parkway,,Y,N
6,1015,Toby Flenderson,304-762-2467,214,HR Avenue,,N,N
7,1016,Ron Weasley,123-545-5421,2395,Hogwarts Avenue,,N,N
8,1017,Michael Scott,123-643-9775,121,Paper Avenue,Pennsylvania,Y,N
9,1020,Anakin Skywalker,876-678-3469,910,Tatooine Road,Tatooine,Y,N